# Generated by Django 5.1.1 on 2024-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(blank=True, to='backend.user'),
        ),
    ]
