# Generated by Django 5.1.1 on 2024-10-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_post_likes_post_liked_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_id',
            new_name='likes',
        ),
    ]
